name: News Finder

on:
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests

      - name: Run News Finder
        run: python scripts/news_finder.py
